### PR TITLE
fix(deps): unblock CI from libcellml 0.7.0 (pin <0.7.0 + renamed-API shims)

### PR DESCRIPTION
**Pull request by FinbarArgus**
CI has been red on `master` since 2026-07-09 for reasons unrelated to any code change.

libCellML 0.7.0 was released that day. `pyproject.toml` asked for `libcellml>=0.6.3` with no upper bound, so every fresh CI run started resolving 0.7.0, and every test that generates a model began failing with:

```
AttributeError: 'Analyser' object has no attribute 'model'
```

This is dependency drift, not a regression: the last green run on master (2026-06-18) resolved libcellml 0.6.3; runs from 2026-07 resolve 0.7.0 and die. It affects every open PR branched off master (#254, #255, #260, #261, #263) — the failure reproduces on `master` itself.

## How 0.7.0 breaks us

1. `Analyser.model()` renamed to `Analyser.analyserModel()`
   → `AttributeError: 'Analyser' object has no attribute 'model'`
2. `Generator.setModel()` / `setProfile()` dropped; the analysed model and profile are now passed as arguments to `interfaceCode()` / `implementationCode()`
   → `AttributeError: 'Generator' object has no attribute 'setProfile'`
3. The generated Python code no longer defines `VARIABLE_COUNT`, which `PythonGenerator` reads out of the generated namespace
   → `KeyError: 'VARIABLE_COUNT'`
4. Units are resolved differently when flattening: SN_simple then fails to connect `a_2` between `soma_SN_module` and `soma_SN` (`Found Units mol_per_m3 and per_millimolar`)

## What this PR does

(1) and (2) are mechanical, and are handled here by `get_analysed_model()`, `generate_interface_code()` and `generate_implementation_code()` in `utilities/libcellml_helper_funcs.py`. They pick the API by feature detection, so they work on both 0.6.x and 0.7.x. The four `analyser.model()` call sites — `CVSCellMLGenerator`, `CVSCppGenerator`, `PythonGenerator`, `generate_modules_files` — are routed through the accessor.

(3) and (4) are a real migration and are **not** attempted here.

So the dependency is pinned to `<0.7.0`, which is what actually restores a green CI, and the shims stay so the eventual 0.7 migration only has to deal with (3) and (4).

## Verification

Verified in a clean CI-like venv (python 3.10, the exact CI pytest command): libcellml resolves to 0.6.3 and `tests/test_param_id.py` + `tests/test_sensitivity_analysis.py` give **45 passed, 0 failed**.

Also re-ran the specific test that surfaced this, under the OpenCOR shell:
`tests/test_param_id.py::test_3compartment_nonstiff_casadi_forward_and_gradient` — **PASSED**.

Note that the local OpenCOR environment already carries libcellml 0.6.3, so that run confirms the shims do not regress 0.6.x rather than exercising 0.7.0; the pin is what protects CI.

**Pre-existing, unrelated:** the `test (3.9/3.10/3.11)` matrix job is a separate failure — it was already red on master on 2026-06-18 under libcellml 0.6.3, so it is not caused by this PR or by the libcellml release.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by FinbarArgus** [comment]
Closing as already landed.

This PR's content reached `master` via the #272 → #274 merge chain, which carried an equivalent commit under a different SHA (`f8c8080` in `master` vs `9db7eab` on this branch). GitHub matches merged state by commit SHA rather than by content, so it could not detect that and left this open.

Verified rather than assumed — rebasing this branch onto the current `master` (`471270a`) drops every commit as already applied and leaves an **empty diff**:

```
$ git rebase upstream/master
warning: skipped previously applied commit a9e294e
warning: skipped previously applied commit 9db7eab
$ git log --oneline upstream/master..HEAD    # (no output)
$ git diff --stat upstream/master...HEAD     # (no output)
```

The pin is present in `master`'s `pyproject.toml` (`libcellml>=0.6.3,<0.7.0`) and the renamed-API shims are in `src/utilities/libcellml_helper_funcs.py`.

Nothing is lost by closing. Reopen if you spot something that did not carry across.
